ExceptionTryCatchFinallyWhen.Program.<Main>g__Throw|0_0[void..()]
Trace:
	[start] ExceptionTryCatchFinallyWhen.Program.<Main>g__Throw|0_0[void..()]
	[ end ] ExceptionTryCatchFinallyWhen.Program.Main[void..(class.System.String[])]


